### PR TITLE
Fix simple-bar examples (special workspaces)

### PR DESCRIPTION
**Pull request by rRedLim**
if you use special workspace, then u will see that weird -99 workspace in ur workspaces,
you cant interact with it, and it doesnt show if it is active or no, so basically useless and ugly
2024-12-08-173713_hyprshot
2024-12-08-173818_hyprshot

### CODE REVIEW

**Comment by rRedLim** [comment]
image
looks like special workspaces are -99...-2 ids
so now it will filter all special workspaces

**Comment by rRedLim** [comment]
bruh now it definitely works xd

**Comment by Aylur** [comment]
Should be also done in all three other simple bar examples with a comment explaining what id does

**Comment by rRedLim** [comment]
> explaining what id does

wdym?

**Pull request merged**
